name: Build USC Sandbox

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build-usc-sandbox:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Set up .NET 8.0
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: "8.0.x"

      - name: Install dependencies
        run: |
          dotnet restore

      - name: Build solution
        run: |
          dotnet build -c Release

      - name: Get git revision
        id: git-revision-check
        shell: bash
        run: |
          export GIT_REF="${GITHUB_REF##*/}"
          echo "GIT_REF=${GIT_REF}" >> $GITHUB_OUTPUT

      - uses: actions/upload-artifact@v7
        with:
          name: "USCSandbox-${{ steps.git-revision-check.outputs.GIT_REF }}"
          path: ./USCSandbox/bin/Release/net8.0/*
